Yewscion changes
museoa/bqn-mode pull request #7
Opened 2022-08-07 21:42 UTC by yewscion

Hello All,

I've made a number of changes to the way the code works here, but I believe they are for the better.

I'll mostly let the commits speak for themselves, but in short, this PR:

- Changes the default interpreter to "bqn" instead of "BQN".
- Fixes the BQN Keymap to assume a font is used to display the bqn glyphs.
- Adds a secondary helper buffer, bqn-glyphs-mode, that is a table with symbol names.
- Fixes the bqn-process-execute-region procedure to properly handle multiline listings for CBQN, per https://github.com/dzaima/CBQN/issues/29.
- Adds a bqn-process-execute-region-follow procedure.
- Adds default keybinds for the execute procedures.
- Shortens the displayed names of some of the more verbose glyphs so the glyphs-mode table can fit in < 80 column displays.

2022-08-07 21:44 UTC, yewscion commented
Opened Issue #8 to track this PR as an issue.

2022-08-10 16:26 UTC, yewscion commented
Please let me know if there are any concerns found within these commits; I am more than willing to help address them in order to get these changes merged.

2022-09-14 02:12 UTC, AndersonTorres commented
Sorry by the delay. I will look at them along this week.

2022-09-14 02:28 UTC, AndersonTorres requested changes

2022-09-14 02:28 UTC, AndersonTorres commented on bqn-comint.el
> +    (insert (format ")escaped \"%s\""
Reword this commit as below:

> Enables buffer and region evals.

> Following the recommendations from https://github.com/dzaima/CBQN/issues/29

As a rule of thumb, the title should be a short, imperative description of the change you want to implement. The body of commit message is filled with the comments you deem necessary.

2022-09-14 02:28 UTC, AndersonTorres commented on bqn-glyphs.el
> +(provide 'bqn-glyphs)
New files should be added in a single commit. Squash those smaller mistakes.

2022-09-14 02:28 UTC, AndersonTorres commented on bqn-glyphs.el
> +(provide 'bqn-glyphs)
Being more accurate: if you are adding a new file, it should not be split between commits.

2022-09-14 17:40 UTC, yewscion commented
I have reworded and squashed my changes into two commits: One solely for the keyboard/glyphs/fonts/etc, and one for the region/buffer execution and configuration. Let me know if this is acceptable!

2022-09-15 00:29 UTC, AndersonTorres requested changes

2022-09-15 00:29 UTC, AndersonTorres commented on bqn-comint.el
> +(defun bqn-process-execute-region (start end &optional dont-follow return-output)
1. Add a blank line between functions;
2. Docstring them:
   
   https://www.gnu.org/software/emacs/manual/html_node/elisp/Documentation-Tips.html

3. More generally, [follow the guide](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html).

2022-09-15 00:29 UTC, AndersonTorres commented on bqn-comint.el
> +(defun bqn-process-execute-region-setup (start end session region)
If the function should be hidden, not meant to be consumed by the end user, prefix it with double-hyphen, `bqn--`

https://github.com/bbatsov/emacs-lisp-style-guide#naming

2022-10-19 01:52 UTC, AndersonTorres commented
I have merged some changes, and the other I tried to understand without success.

2022-10-19 15:47 UTC, yewscion commented
Copy that. I apologize for my radio silence, other things have been demanding my attention.

I will review what was merged and fix what wasn't. Thank You for Your efforts and communication.

2023-03-20 01:49 UTC, AndersonTorres commented
Closing as unable to understand and full of conflicting entries.

2023-03-20 01:49 UTC, closed without merging